CREATE DATABASE portfolio SET 'utf8';

CREATE TABLE Parametres_utilisateur(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	nom VARCHAR(30) NOT NULL,
	prénom VARCHAR(30) NOT NULL,
	age INT(3) NOT NULL,
	sexe CHAR(1) NOT NULL,
	numéro_de_tél INT(15),
	addresse_mail VARCHAR(30),
	PRIMARY KEY (id))
ENGINE = INNODB;

CREATE TABLE Contact(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	nom VARCHAR(30) NOT NULL,
	adresse VARCHAR(30) NOT NULL,
	numéro_de_tél INT(15) NULL,
	adresse_mail VARCHAR(30) NULL,
	PRIMARY KEY (id))
ENGINE = INNODB;

CREATE TABLE Acueil(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	PRIMARY KEY (id))
ENGINE = INNODB;

CREATE TABLE Admin(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	log_admin VARCHAR(20) NOT NULL,
	email_admin VARCHAR(40) NOT NULL,
	mdp_admin VARCHAR(50) NOT NULL,
	PRIMARY KEY (id))
ENGINE = INNODB;

CREATE TABLE Menu(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	affiche_menu INT(1),
	ordre_menu INT(2),
	id_langue INT(4),
	PRIMARY KEY (id))
ENGINE = INNODB;

CREATE TABLE Langue(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	nom VARCHAR(20) NOT NULL,
	PRIMARY KEY (id))
ENGINE = INNODB;

CREATE TABLE Page(
	id SMALLINT UNSIGNED NOT NULL AUTO_INCREMENT,
	nom VARCHAR(30) NOT NULL,
	affiche_page INT(2)NOT NULL,
	PRIMARY KEY (id))
ENGINE = INNODB;